//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineShop.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the Latest Trends.
        /// </summary>
        public static string DiscoverTheLatestTrends {
            get {
                return ResourceManager.GetString("DiscoverTheLatestTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Products.
        /// </summary>
        public static string ExploreProducts {
            get {
                return ResourceManager.GetString("ExploreProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion-forward pieces for every style and mood..
        /// </summary>
        public static string FashionForward {
            get {
                return ResourceManager.GetString("FashionForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the perfect look for any occasion..
        /// </summary>
        public static string FindThePerfect {
            get {
                return ResourceManager.GetString("FindThePerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men&apos;s Collection.
        /// </summary>
        public static string Men_sCollection {
            get {
                return ResourceManager.GetString("Men\'sCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay stylish with our new arrivals for every season..
        /// </summary>
        public static string StayStylish {
            get {
                return ResourceManager.GetString("StayStylish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Fashion Shop!.
        /// </summary>
        public static string WelcomeToFashionShop {
            get {
                return ResourceManager.GetString("WelcomeToFashionShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women&apos;s Collection.
        /// </summary>
        public static string Women_sCollection {
            get {
                return ResourceManager.GetString("Women\'sCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your one-stop shop for all your needs, from essentials to luxury items..
        /// </summary>
        public static string YourOne_stopShopForAllYourNeeds {
            get {
                return ResourceManager.GetString("YourOne-stopShopForAllYourNeeds", resourceCulture);
            }
        }
    }
}
